---
kind: pipeline
name: default

trigger:
  branch:
    - master

steps:
  - name: deps
    image: node:22-alpine
    commands:
      - corepack pnpm install --frozen-lockfile

  - name: lint
    image: node:22-alpine
    commands:
      - corepack pnpm run lint

  - name: format
    image: node:22-alpine
    commands:
      - corepack pnpm run fmt:check

  - name: typecheck
    image: node:22-alpine
    commands:
      - corepack pnpm run type

  - name: build
    image: node:22-alpine
    commands:
      - corepack pnpm run build
