export enum DnsRecordTypeEnum {
    A = "A",
    AAAA = "AAAA",
    CNAME = "CNAME",
    CAA = "CAA",
    TXT = "TXT",
    SRV = "SRV",
    LOC = "LOC",
    MX = "MX",
    NS = "NS",
    SPF = "SPF",
    CERT = "CERT",
    DNSKEY = "DNSKEY",
    DS = "DS",
    NAPTR = "NAPTR",
    SMIMEA = "SMIMEA",
    SSHFP = "SSHFP",
    TLSA = "TLSA",
    URI = "URI",
    PTR = "PTR",
    HTTPS = "HTTPS",
    SVCB = "SVCB",
}
